id: IAEACEBC5
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T04:45:09+00:00'
last_modified: '2022-06-08T13:53:32.300823+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG14139
  title: ཀླད་ཆེན་དང་སེམས་ཀྱི་འབྲེལ་བ་ལ་དཔྱད་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    B8D0:
      image_group_id: I1KG14334
      title: ''
      total_pages: 124
      order: 1
      base_file: B8D0.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
