id: P010477
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-19 20:51:51.909944
source_metadata:
  id: bdr:W1KG14139
  title: ཀླད་ཆེན་དང་སེམས་ཀྱི་འབྲེལ་བ་ལ་དཔྱད་པ།
  author: ''
  volumes:
    95f65aa29d404ad0ae2fecadeb2eb155:
      image_group_id: I1KG14334
      title: ''
      volume_number: 1
      total_pages: 124
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
